### ISSUE TITLE
Where are internships? Its already March

### ISSUE THREAD

**Issue by jahaskell53** [bsovs/Fall2024-Internships#154]

**Comment by josephmasson26** [comment]
real

**Comment by mxsaad** [comment]
+1

**Comment by taha5322** [comment]
Maybe they won't be maintaining fall. Anyone know any other repos?

**Comment by jdkuffa** [comment]
i opened a pull request with some openings, any idea how to get it reviewed and merged?

**Comment by Gnoot01** [comment]
> i opened a pull request with some openings and it's been reviewed and will hopefully be merged soon. those contributions should show up in the README promptly.

Hi, if you don't mind, do you mind sharing your edits? seems like the owner of this repo is inactive. Thanks!

**Comment by bsovs** [comment]
At long last I am back.
Sorry for the long wait, been chronically offline. 
Check out: https://simplify.jobs/l/Top-Fall-Internships
And set the little bell on: https://www.linkedin.com/jobs/search/?currentJobId=3922205766&f_E=1&geoId=103644278&keywords=fall%20internship&location=United%20States&origin=JOB_SEARCH_PAGE_JOB_FILTER&refresh=true

I'll see if I can work with Simplify to co-maintain this or something, since I am definitely not the most reliable maintainer anymore due to not coding on this account. 

![image](https://github.com/bsovs/Fall2024-Internships/assets/18584579/44889d49-8e5c-4144-81a8-39300f2b7e81)
